version: '3'
services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    ports:
      - "5678:5678"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always  # Riavvia sempre il servizio

  db:
    image: postgres:13
    container_name: telegram_bot_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always  # Riavvia sempre il servizio

volumes:
  db_data: